[registries]

OxidizerTest = { index = "sparse+https://o365exchange.pkgs.visualstudio.com/959adb23-f323-4d52-8203-ff34e5cbeefa/_packaging/OxidizerTest/Cargo/index/" }

OxidizerDependencies = { index = "sparse+https://o365exchange.pkgs.visualstudio.com/959adb23-f323-4d52-8203-ff34e5cbeefa/_packaging/OxidizerDependencies/Cargo/index/" }

[source.crates-io]
replace-with = "OxidizerDependencies"
